# Generated by Django 4.2.5 on 2023-09-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_image',
            field=models.ImageField(upload_to='sample_images/'),
        ),
    ]
