# Generated by Django 4.2.5 on 2023-09-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0002_rename_name_sample_name_alter_sample_sample_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_image',
            field=models.ImageField(upload_to='samples/'),
        ),
    ]
