# Generated by Django 4.2.5 on 2023-10-01 02:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyser', '0004_sample_analysis_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='sample_image'),
        ),
    ]
